### ISSUE TITLE
there is a situation when msg queue is not empty, but these msgs are not delivered and nothing happens

### ISSUE THREAD

**Issue by KseniyaYakil** [edenhill/librdkafka#2033]
Description
===========
there is a situation when msg queue is not empty, but these msgs are not delivered and nothing happens.

How to reproduce
================
run program rdkafka_queue_test (gcc rdkafka_queue_producer.c /usr/local/lib/librdkafka.a  -ldl -lz  -lpthread -lrt -lm -o rdkafka_queue_test)

./rdkafka_queue_test <kafka_brokers_list> <topic_name> 100000

it doesn't fail always, but the frequency of reproducing is high, just run several times this program or change msg_cnt parameter (it reproduced with 50000 too)

test program has the following logic: add msg batches via rd_kafka_produce_batch() call, wait and try again if queue is full.  after all messages are enqueued, wait for all msgs delivery with nanosleep() and rd_kafka_poll() calls.
 
according to stats from librdkafka there is kafka1.d3 broker (which is the leader) with empty outbufs. but there is msg_cnt != 0 in librdkafka queue. periodic stats (which is printed every 10 seconds) shows that state is not changed (no in flight requests too). strace and gdb + bt shows that there are calls of poll(POLLIN), futex, nano sleeps and sometimes madvise/mmap calls.

Checklist
=========
 - [x] librdkafka version: v0.11.5 (./configure --disable-ssl --enable-static)
 - [x] Apache Kafka version: kafka 0.9.0.1 and kafka 0.11.0.0
 - [x] librdkafka client configuration:
debug= "all";
broker.version.fallback= "0.10.1";
queue.buffering.max.messages= "100000";
queue.buffering.max.ms= "100";
queue.buffering.max.kbytes= "1269532";
batch.num.messages= "300";
max.in.flight.requests.per.connection= "10";
message.send.max.retries= "3600";
retry.backoff.ms= "500";
compression.codec= "snappy";
socket.timeout.ms= "300000";
socket.max.fails= "0";
socket.keepalive.enable= "true";
topic.metadata.refresh.interval.ms= "180000";
request.required.acks= "1";
request.timeout.ms= "30000";
message.timeout.ms= "0";
log.connection.close= "false";
log.level= "3";
statistics.interval.ms= "10000";
 - [x] Operating system: Linux 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
test program code, program and kafka logs, bt of program are available here https://gist.github.com/KseniyaYakil/dbdffda74069fb00d198fcfc86cf58ed
 - [x] Provide broker log excerpts
https://gist.github.com/KseniyaYakil/dbdffda74069fb00d198fcfc86cf58ed
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thank you for a great report!

I think there might be issues with `message.timeout.ms=0`, could you try setting it to a non-zero positive value, such as the max value 300000?

**Comment by KseniyaYakil** [comment]
Thank you for your immediate answer)

Changed message.timeout.ms=300000 but the problem still presents

I also found the problem occurs after all msgs are produced via rd_kafka_produce_batch() and there is the following message in log 
7: TOPPAR: [thrd:kafka1.d3:9092/bootstrap]: kafka1.d3:9092/1: kseniya_rdkafka_test [0] 49384 message(s) in xmit queue (49384 added from partition queue
the rest 616 messages won’t be delivered (expect to deliver 50000 msgs to kafka)

previous messages in log are:

7: STATE: [thrd:main]: Topic kseniya_rdkafka_test changed state unknown -> exists
7: PARTCNT: [thrd:main]: Topic kseniya_rdkafka_test partition count changed from 0 to 1
7: TOPPARNEW: [thrd:main]: NEW kseniya_rdkafka_test [0] 0x7f4a1c001020 (at rd_kafka_topic_partition_cnt_update:587)
7: METADATA: [thrd:main]:   Topic kseniya_rdkafka_test partition 0 Leader 1
7: BRKDELGT: [thrd:main]: kseniya_rdkafka_test [0]: delegate to broker (none) (rktp 0x7f4a1c001020, term 0, ref 2, remove 0)
7: BRKDELGT: [thrd:main]: kseniya_rdkafka_test [0]: broker :0/internal is now leader for partition with 0 messages (0 bytes) queued
7: BRKMIGR: [thrd:main]: Migrating topic kseniya_rdkafka_test [0] 0x7f4a1c001020 from (none) to :0/internal (sending PARTITION_JOIN to :0/internal)
7: PARTCNT: [thrd:main]: Partitioning 14384 unassigned messages in topic kseniya_rdkafka_test to 1 partitions
7: TOPBRK: [thrd::0/internal]: :0/internal: Topic kseniya_rdkafka_test [0]: joining broker (rktp 0x7f4a1c001020)
7: FETCHADD: [thrd::0/internal]: :0/internal: Added kseniya_rdkafka_test [0] to active list (1 entries, opv 0)
7: UAS: [thrd:main]: 14384/14384 messages were partitioned in topic kseniya_rdkafka_test
7: METADATA: [thrd:main]: kafka2.d3:9092/bootstrap: 1/1 requested topic(s) seen in metadata
7: CLUSTERID: [thrd:main]: kafka2.d3:9092/bootstrap: ClusterId update "" -> "6qONqqYxTuSQTyJGH-ENwQ"
7: CONTROLLERID: [thrd:main]: kafka2.d3:9092/bootstrap: ControllerId update -1 -> 1
7: UPDATE: [thrd:kafka1.d3:9092/bootstrap]: kafka1.d3:9092/bootstrap: NodeId changed from -1 to 1
7: UPDATE: [thrd:kafka1.d3:9092/bootstrap]: kafka1.d3:9092/1: Name changed from kafka1.d3:9092/bootstrap to kafka1.d3:9092/1
7: TOPICUPD: [thrd:kafka1.d3:9092/bootstrap]: Topic kseniya_rdkafka_test [0] migrated from broker -1 to 1
7: BRKDELGT: [thrd:kafka1.d3:9092/bootstrap]: kseniya_rdkafka_test [0]: delegate to broker kafka1.d3:9092/1 (rktp 0x7f4a1c001020, term 0, ref 3, remove 0)
7: BRKDELGT: [thrd:kafka1.d3:9092/bootstrap]: kseniya_rdkafka_test [0]: broker :0/internal no longer leader
7: BRKDELGT: [thrd:kafka1.d3:9092/bootstrap]: kseniya_rdkafka_test [0]: broker kafka1.d3:9092/1 is now leader for partition with 14429 messages (1515045 bytes) queued
7: BRKMIGR: [thrd:kafka1.d3:9092/bootstrap]: Migrating topic kseniya_rdkafka_test [0] 0x7f4a1c001020 from :0/internal to kafka1.d3:9092/1 (sending PARTITION_LEAVE to :0/internal)
7: LEADER: [thrd:kafka1.d3:9092/bootstrap]: kafka1.d3:9092/1: Mapped 1 partition(s) to broker
7: STATE: [thrd:kafka1.d3:9092/bootstrap]: kafka1.d3:9092/1: Broker changed state UP -> UPDATE
7: STATE: [thrd:kafka1.d3:9092/bootstrap]: kafka1.d3:9092/1: Broker changed state UPDATE -> UP
7: TOPBRK: [thrd::0/internal]: :0/internal: Topic kseniya_rdkafka_test [0]: leaving broker (0 messages in xmitq, next leader kafka1.d3:9092/1, rktp 0x7f4a1c001020)
7: FETCHADD: [thrd::0/internal]: :0/internal: Removed kseniya_rdkafka_test [0] from active list (0 entries, opv 0)
7: UPDATE: [thrd:kafka2.d3:9092/bootstrap]: kafka2.d3:9092/bootstrap: NodeId changed from -1 to 2
7: UPDATE: [thrd:kafka2.d3:9092/bootstrap]: kafka2.d3:9092/2: Name changed from kafka2.d3:9092/bootstrap to kafka2.d3:9092/2
7: LEADER: [thrd:kafka2.d3:9092/bootstrap]: kafka2.d3:9092/2: Mapped 0 partition(s) to broker
7: TOPBRK: [thrd:kafka1.d3:9092/bootstrap]: kafka1.d3:9092/1: Topic kseniya_rdkafka_test [0]: joining broker (rktp 0x7f4a1c001020)
7: STATE: [thrd:kafka2.d3:9092/bootstrap]: kafka2.d3:9092/2: Broker changed state UP -> UPDATE
7: FETCHADD: [thrd:kafka1.d3:9092/bootstrap]: kafka1.d3:9092/1: Added kseniya_rdkafka_test [0] to active list (1 entries, opv 0)
7: STATE: [thrd:kafka2.d3:9092/bootstrap]: kafka2.d3:9092/2: Broker changed state UPDATE -> UP

Noticed the following:
1) if I use patrition_id=RD_KAFKA_PARTITION_UA instead of partition_id=0 the problem is not reproduced
2) if I use sleep(3) after rd_kafka_new(); rd_kafka_topic_new() , the problem is not reproduced too

May be there is a race between establishing connection to brokers/detecting partitions and parallel msg enqueueing, what do you think?

**Comment by edenhill** [comment]
You could be hitting this issue: https://github.com/edenhill/librdkafka/issues/1985

It'd be great if you could try reproducing on master branch where this issue is fixed.

**Comment by KseniyaYakil** [comment]
build from master (last commit b677b451700a3) with --disable-ssl --enable-static
still reproduced

**Comment by KseniyaYakil** [comment]
[rdkafka_queue_producer.log](https://github.com/edenhill/librdkafka/files/2437831/rdkafka_queue_producer.log)
message.timeout.ms=0

**Comment by edenhill** [comment]
I have a strong recollection of fixing a bug like this recently.
Could I ask you for one more thing? Reproduce this on the https://github.com/edenhill/librdkafka/tree/sparseconnections branch?

**Comment by KseniyaYakil** [comment]
yes, sure)

the same behaviour
[rdkafka_queue_producer_sparseconnections.log](https://github.com/edenhill/librdkafka/files/2437924/rdkafka_queue_producer_sparseconnections.log)

**Comment by KseniyaYakil** [comment]
Thank you for taking the time to help

**Comment by edenhill** [comment]
I've found the issue:
in produce_batch(), when a specific partition is passed, the partition object is looked up on entering the function. If the partition is not yet known it will default to the ua partition (unassigned, -1).
While the batch code runs, metadata is learned and the partition is created and any messages on the ua partition are moved over to the newly detected partitions. But the batch code still enqueues to the UA partition so any messages still being processed by the batch() call will go to the UA, where they will be stuck.

We'll fix this in the release after the upcoming v0.11.6 maintenance.
The workaround for now is either calling rd_kafka_metadata() on the topic before starting to produce, or not using the produce_batch() function.

Do note that produce_batch() does not correlate to the batches in the Kafka protocol, those are accumulated separately from the internal partition queue. The only reason for produce_batch() is to minimize the number of function calls, but this is not an issue when calling from C or C++, but rather with high-level languages such as Golang that has a high C call overhead.

**Comment by KseniyaYakil** [comment]
calling rd_kafka_metadata() helps to solve this problem!
thanks a lot for your help and detailed description)
