### ISSUE TITLE
librdkafka doesn't compile in Alpine Linux

### ISSUE THREAD

**Issue by scordeiro** [edenhill/librdkafka#565]
Hi,

I can't compile `librdkafka` in [Alpine Linux](http://www.alpinelinux.org) without a manual workaround.

The `rdendian.h` header file has some macros to load `endian.h` and, since Alpine Linux uses [MUSL libc](http://www.musl-libc.org/) and macros like `__GLIBC__` are not present, since [__MUSL__ is not implemented in it](http://wiki.musl-libc.org/wiki/FAQ) compilation fails.

This is the error, `configure` was run with `--prefix=/usr` parameter since Alpine doesn't use the `/usr/local`:
```C
# make
make[1]: Entering directory '/build/librdkafka-0.9.12346/src'
gcc -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith   -c rdkafka.c -o rdkafka.o
In file included from rdkafka_proto.h:32:0,
                 from rdkafka_msg.h:33,
                 from rdkafka_op.h:31,
                 from rdkafka_int.h:99,
                 from rdkafka.c:38:
rdendian.h:106:4: error: #error Unknown location for endian.h
   #error Unknown location for endian.h
    ^
../mklove/Makefile.base:75: recipe for target 'rdkafka.o' failed
make[1]: *** [rdkafka.o] Error 1
make[1]: Leaving directory '/build/librdkafka-0.9.12346/src'
Makefile:20: recipe for target 'libs' failed
make: *** [libs] Error 2
```

To fix this, I replaced the `#error Unknown location for endian.h` line with `#include <endian.h>` in `rdendian.h` but it doesn't seem to be the best solution, I don't know if there's a better way, MUSL seems to have some information on how to do that in the [link shared in FAQ](http://openwall.com/lists/musl/2013/03/29/13)'s question `why is there no __MUSL__ macro ?`.

**NOTE**: To compile `librdkafka` in Alpine, the following packages were added to the base image (I use Alpine for small Docker builds) with the following command:
  * apk add --no-cache python openssl yajl-dev zlib-dev cyrus-sasl-dev openssl-dev build-base coreutils bash

**Comment by scordeiro** [comment]
FYI, this is the output of the `configure --prefix=/usr`:

```sh
# ./configure --prefix=/usr
checking for OS or distribution... ok (Linux)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x00090100'... ok (0.9.1)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for zlib (by pkg-config)... ok
checking for libcrypto (by pkg-config)... ok
checking for libssl (by pkg-config)... ok
checking for libsasl2 (by pkg-config)... ok
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for strndup (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_SSL               y
  ENABLE_SASL              y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  MKL_DISTRO               Linux
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.9.1
  MKL_APP_VERSION          0.9.1
  LIBS                     -lpthread -L/lib -lz   -lcrypto   -lssl   -L/lib -lsasl2   -lrt
  CFLAGS
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /usr
  bindir                   /usr/bin
  sbindir                  /usr/sbin
  libexecdir               /usr/libexec
  datadir                  /usr/share
  sysconfdir               /usr/etc
  sharedstatedir           /usr/com
  localstatedir            /usr/var
  libdir                   /usr/lib
  includedir               /usr/include
  infodir                  /usr/info
  mandir                   /usr/man
Generated config.cache

Now type 'make' to build
```

**Comment by edenhill** [comment]
Thanks, I will look into this.

**Comment by edenhill** [comment]
Small note: librdkafka itself does not depend on libyajl, but kafkacat does (optionally).

**Comment by edenhill** [comment]
There, that should fix it. Please verify on your side.

**Comment by scordeiro** [comment]
@edenhill Looks good! Thanks!

**Comment by 3kwa** [comment]
I think this issue is back - just tried to build a docker image based on alpine

`Step 10/17 : RUN go get -u gopkg.in/confluentinc/confluent-kafka-go.v1/kafka
 ---> Running in 4ee14590af90
# gopkg.in/confluentinc/confluent-kafka-go.v1/kafka
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /go/src/gopkg.in/confluentinc/confluent-kafka-go.v1/kafka/librdkafka/librdkafka_glibc_linux.a(rdkafka_txnmgr.o): in function `rd_kafka_txn_set_fatal_error':
(.text+0x141): undefined reference to `__strdup'`

**Comment by edenhill** [comment]
Build with -tags musl
